/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RAM_START			0x20000000U
#define RAM_SIZE			((128)*(1024U))
#define RAM_END				RAM_START+RAM_SIZE
#define TASK_STACK_SIZE		1024U
#define SCHED_STACK_SIZE	1024U

#define SYS_CLK 			16000000U
#define Tick_Hz				1000U

#define TASK1_STACK_START	RAM_END
#define TASK2_STACK_START	(RAM_END-(1*TASK_STACK_SIZE))
#define TASK3_STACK_START	(RAM_END-(2*TASK_STACK_SIZE))
#define TASK4_STACK_START	(RAM_END-(3*TASK_STACK_SIZE))
#define IDLE_STACK_START	(RAM_END-(4*TASK_STACK_SIZE))
#define SCHED_STACK_START	(RAM_END-(5*TASK_STACK_SIZE))


void Task1_handler(void);
void Task2_handler(void);
void Task3_handler(void);
void Task4_handler(void);
void IdleTask_handler(void);
__attribute__((naked)) void switch_sp_to_psp(void);

void systick_init(uint32_t TickHz);
void task_stack_init(void);
__attribute__((naked)) void sched_stack_init(uint32_t sched_top_of_stack);

void save_psp_value(uint32_t psp_value);
void update_next_task(void);
uint32_t get_psp_value(void);
void enable_processor_faults(void);
void task_delay(uint32_t TickCount);
void do_context_switch(void);
uint32_t g_tick=0;

//uint32_t psp_of_task[4]={TASK1_STACK_START,TASK2_STACK_START,TASK3_STACK_START,TASK4_STACK_START};
//uint32_t task_handler[4];

uint8_t current_task=1;
#define TASK_STATE_RUNNING	0x00
#define TASK_STATE_BLOCK	0xFF



typedef struct
{
	uint32_t psp_value;
	uint32_t current_state;
	uint32_t block_count;
	void (*task_handler)(void);
}TCB_t;

TCB_t usertask[5];

int main(void)
{

	enable_processor_faults();

	sched_stack_init(SCHED_STACK_START);

	task_stack_init();

	led_init_all();
	systick_init(Tick_Hz);
	switch_sp_to_psp();

	Task1_handler();

    /* Loop forever */
	for(;;);
}

void Task1_handler(void)
{
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}
void Task2_handler(void)
{
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}
void Task3_handler(void)
{
	while(1)
	{
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}
}

void Task4_handler(void)
{
	while(1)
	{
		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}
}

void IdleTask_handler(void)
{
	while(1)
	{

	}
}

void systick_init(uint32_t TickHz)
{
	uint32_t *pSYST_RVR=(uint32_t*)0xE000E014;
	uint32_t *pSYST_CSR=(uint32_t*)0xE000E010;

	uint32_t count= (SYS_CLK/TickHz)-1;

	*pSYST_RVR &= ~(0xFFFFFF);
	*pSYST_RVR |= count;

	*pSYST_CSR |= 1<<2;
	*pSYST_CSR |= 1<<1;
	*pSYST_CSR |= 1<<0;

}


void task_stack_init(void)
{
	uint32_t *ptr=NULL;

	usertask[0].current_state=TASK_STATE_RUNNING;
	usertask[1].current_state=TASK_STATE_RUNNING;
	usertask[2].current_state=TASK_STATE_RUNNING;
	usertask[3].current_state=TASK_STATE_RUNNING;
	usertask[4].current_state=TASK_STATE_RUNNING;

	usertask[0].task_handler=IdleTask_handler;
	usertask[1].task_handler=Task1_handler;
	usertask[2].task_handler=Task2_handler;
	usertask[3].task_handler=Task3_handler;
	usertask[4].task_handler=Task4_handler;

	usertask[0].psp_value=IDLE_STACK_START;
	usertask[1].psp_value=TASK1_STACK_START;
	usertask[2].psp_value=TASK2_STACK_START;
	usertask[3].psp_value=TASK3_STACK_START;
	usertask[4].psp_value=TASK4_STACK_START;

	for(int i=0;i<5;i++)
	{
		ptr=(uint32_t*)usertask[i].psp_value;

		ptr--;
		*ptr=0x01000000;

		ptr--;
		*ptr=(uint32_t)usertask[i].task_handler;

		ptr--;
		*ptr=0xFFFFFFFD;

		for(int j=0;j<13;j++)
		{
			ptr--;
			*ptr=0;
		}

		usertask[i].psp_value=(uint32_t)ptr;
	}

}

__attribute__((naked)) void sched_stack_init(uint32_t sched_top_of_stack)
{
	__asm volatile("MSR MSP,R0");
	__asm volatile("BX LR");
}

uint32_t get_psp_value(void)
{
	return usertask[current_task].psp_value;
}

__attribute__((naked)) void switch_sp_to_psp(void)
{

	__asm volatile("PUSH {LR}");
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP,R0");

	__asm volatile("POP {LR}");
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}

void save_psp_value(uint32_t current_psp_value)
{
	usertask[current_task].psp_value=current_psp_value;
}

void update_next_task(void)
{
	int state=TASK_STATE_BLOCK;

	for(int i=0;i<5;i++)
	{

		current_task++;
		current_task=current_task%5;
		state=usertask[current_task].current_state;
		if( state == TASK_STATE_RUNNING && current_task !=0)
			break;

	}

	if(state != TASK_STATE_RUNNING)
		current_task=0;

}


__attribute__((naked)) void PendSV_Handler(void)
{
	//1. get the value of PSP
	__asm volatile("MRS R0,PSP");
	//2. Save R4-R11
	__asm volatile("STMDB R0!,{R4-R11}");
	//3. PUSH LR and branch to function to Save the PSP value
	__asm volatile("PUSH {LR}");
	__asm volatile("BL save_psp_value");
	//4. Update next task
	__asm volatile("BL update_next_task");
	//5. Get current psp value
	__asm volatile("BL get_psp_value");
	//6. Retrieve R4-R11
	__asm volatile("LDMIA R0!,{R4-R11}");
	//7. update PSP value as you retrieved the context of R4-R11
	__asm volatile("MSR PSP,R0");
	//8. Retrieve LR and do context switch
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");
}

void update_tick_count(void)
{
	g_tick++;
}

void unblock_task(void)
{

	for(int i=1;i<5;i++)
	{
		if(usertask[i].current_state != TASK_STATE_RUNNING)
		{
			if(usertask[i].block_count==g_tick)
			{
				usertask[i].current_state=TASK_STATE_RUNNING;
			}
		}
	}
}

void do_context_switch()
{
	uint32_t *pICSR= (uint32_t*)0xE000ED04;
	*pICSR= 1<<28;
}

void SysTick_Handler(void)
{
	update_tick_count();
	unblock_task();
	do_context_switch();
}

void HardFault_Handler(void)
{

	printf("Exception :Hard fault\n");
	while(1);
}

void MemManage_Handler(void){
	printf("Exception :Mem Manage fault\n");
	while(1);
}

void  BusFault_Handler(void)
{
	printf("Exception :Bus fault\n");
	while(1);
}

void enable_processor_faults(void)
{
	uint32_t *pSHCSR=(uint32_t*)0xE000ED24;
	*pSHCSR |= 1<<16; //ENable mem,usage,bus faults
	*pSHCSR |= 1<<17;
	*pSHCSR |= 1<<18;
}

void task_delay(uint32_t TickCount)
{
	if(current_task)
	{
	usertask[current_task].block_count=g_tick+TickCount;
	usertask[current_task].current_state=TASK_STATE_BLOCK;
	do_context_switch();
	}
}

